version: 0.2
phases:
  install:
  pre_build:
    commands:
      - aws s3 sync . $APP_BUCKET/
      - AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'